### ISSUE TITLE
config validation fails if Peers list is empty and Type set to redis

### ISSUE THREAD

**Issue by mschfh** [honeycombio/samproxy#147]
config:
```toml
[PeerManagement]
Peers = []
Type = "redis"
RedisHost = "example.com"
```

```
unable to load config: Key: 'configContents.PeerManagement.Peers' Error:Field validation for 'Peers' failed on the 'required' tag
```

if set to the default value (`["http://127.0.0.1:8081"]`) it will be overwritten by the peer list from redis (as expected)
